_target_: lsr.models.DualSparseEncoder
query_encoder:
  config: 
    _target_: lsr.models.TransformerMLMSparseOPTDecoderMultiSteps
    tf_base_model_name_or_dir: facebook/opt-350m

config:
  _target_: lsr.models.DualSparseConfig
  shared: True
  lora: False