_target_: lsr.models.DualSparseEncoder
query_encoder:
  _target_: lsr.models.TransformerMLMSparseEncoder
  config:
    _target_: lsr.models.TransformerMLMConfig
    tf_base_model_name_or_dir: distilbert/distilbert-base-uncased
config:
  _target_: lsr.models.DualSparseConfig
  shared: True
  lora: False