_target_: lsr.models.DualSparseEncoder
query_encoder:
  _target_: lsr.models.TransformerMLPSparseEncoderDecoderSingleSteps
  config: 
    _target_: lsr.models.TransformerMLPEncoderDecoderSingleStepsConfig
    activation: "relu" 
    norm: "identity"

config:
  _target_: lsr.models.DualSparseConfig
  shared: True
  lora: False