_target_: lsr.models.DualSparseEncoder
query_encoder:
    _target_: lsr.models.TransformerMLMSparseOPTDecoderMultiSteps
    config:
      _target_: lsr.models.TransformerMLMOPTDecoderMultiStepsConfig
      tf_base_model_name_or_dir: facebook/opt-2.7b

config:
  _target_: lsr.models.DualSparseConfig
  shared: True
  lora: False