_target_: lsr.models.DualSparseEncoder
query_encoder:
  _target_: lsr.models.TransformerMLPSparseT5DecoderMultiSteps
  config: 
    _target_: lsr.models.TransformerMLPT5DecoderMultiStepsConfig
    activation: "relu" 
    norm: "identity"

config:
  _target_: lsr.models.DualSparseConfig
  shared: True
  lora: False

