_target_: lsr.models.DualSparseEncoder
query_encoder:
  _target_: lsr.models.TransformerMLPSparseEncoder
  config:
    _target_: lsr.models.TransformerMLPConfig
    activation: "relu" 
    norm: "identity"
doc_encoder:
  _target_: lsr.models.BinaryEncoder