_target_: lsr.datasets.TripletIDDistilDataset
collection_path: 'hfds:lsr42/msmarco-passage-doct5query'
queries_path: data/msmarco/train_queries/queries/raw.tsv
qrels_path:  data/msmarco/train_queries/qrels.json
ce_score_dict: data/msmarco/hard_negatives_scores/cross-encoder-ms-marco-MiniLM-L-6-v2-scores.pkl.gz

