_target_: lsr.datasets.TripletIDDistilDataset
collection_path: data/msmarco/full_collection/raw.tsv
queries_path: data/msmarco/train_queries/queries/raw.tsv
qrels_path:  data/msmarco/train_queries/qrels.json
ce_score_dict: data/msmarco/hard_negatives_scores/rankllama-13b-ms-marco-scores.pkl.gz