_target_: lsr.datasets.TripletTextDataset
# collection_path: '/var/scratch/jqiao/lsr_eval/data/toy_data/full_collection/raw.tsv'
# queries_path: '/var/scratch/jqiao/lsr_eval/data/toy_data/dev_queries/raw.tsv'
# triplet_ids_path: '/var/scratch/jqiao/lsr_eval/data/toy_data/triplets/raw.tsv'
data_path: '/var/scratch/jqiao/lsr_eval/data/toy_data/triplets/raw.tsv'
# ce_score_dict: data/msmarco/hard_negatives_scores/cross-encoder-ms-marco-MiniLM-L-6-v2-scores.pkl.gz